main:
  # rleg current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [0],  label: crotch yaw }
  #     - { key: RobotHardware0_tau, id: [32], label: crotch-innner }
  #     - { key: RobotHardware0_tau, id: [33], label: crotch-outer  }
  #     - { key: RobotHardware0_tau, id: [34], label: knee }
  #     - { key: RobotHardware0_tau, id: [35], label: ankle-innner }
  #     - { key: RobotHardware0_tau, id: [36], label: ankle-outer  }

  # lleg current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [6],  label: crotch yaw }
  #     - { key: RobotHardware0_tau, id: [37], label: crotch-innner }
  #     - { key: RobotHardware0_tau, id: [38], label: crotch-outer  }
  #     - { key: RobotHardware0_tau, id: [39], label: knee }
  #     - { key: RobotHardware0_tau, id: [40], label: ankle-innner }
  #     - { key: RobotHardware0_tau, id: [41], label: ankle-outer  }

  # rarm current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [16], label: shoulder roll/pitch}
  #     - { key: RobotHardware0_tau, id: [17], label: shoulder roll/pitch}
  #     - { key: RobotHardware0_tau, id: [18], label: shoulder yaw }
  #     - { key: RobotHardware0_tau, id: [44], label: elbow }
  #     - { key: RobotHardware0_tau, id: [46], label: wrist-inner }
  #     - { key: RobotHardware0_tau, id: [47], label: wrist-outer }
  #     - { key: RobotHardware0_tau, id: [22], label: wrist yaw }

  # larm current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [24], label: shoulder roll/pitch}
  #     - { key: RobotHardware0_tau, id: [25], label: shoulder roll/pitch}
  #     - { key: RobotHardware0_tau, id: [26], label: shoulder yaw }
  #     - { key: RobotHardware0_tau, id: [45], label: elbow }
  #     - { key: RobotHardware0_tau, id: [48], label: wrist-inner }
  #     - { key: RobotHardware0_tau, id: [49], label: wrist-outer }
  #     - { key: RobotHardware0_tau, id: [30], label: wrist yaw }

  # torso current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [42], label: waist right}
  #     - { key: RobotHardware0_tau, id: [43], label: waist left }

  # joint current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [16], label: shoulder roll/pitch}
  #     - { key: RobotHardware0_tau, id: [17], label: shoulder roll/pitch}
  #     - { key: RobotHardware0_tau, id: [18], label: shoulder yaw }
  #     - { key: RobotHardware0_tau, id: [0], label: hip yaw }

  # current:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [32], label: hip-innner }
  #     - { key: RobotHardware0_tau, id: [33], label: hip-outer  }
  #     - { key: RobotHardware0_tau, id: [34], label: knee }
  #     - { key: RobotHardware0_tau, id: [35], label: ankle-innner }
  #     - { key: RobotHardware0_tau, id: [36], label: ankle-outer  }
  #     - { key: RobotHardware0_tau, id: [44], label: elbow }
  #     - { key: RobotHardware0_tau, id: [46], label: wrist-inner }
  #     - { key: RobotHardware0_tau, id: [47], label: wrist-outer }
  # current2:
  #   legends:
  #     - { key: RobotHardware0_tau, id: [22], label: wrist yaw }
  #     - { key: RobotHardware0_tau, id: [42], label: waist right}
  #     - { key: RobotHardware0_tau, id: [43], label: waist left }
  #     - { key: RobotHardware0_tau, id: [16], label: shoulder roll/pitch}
  #     - { key: RobotHardware0_tau, id: [17], label: shoulder roll/pitch}
  #     - { key: RobotHardware0_tau, id: [18], label: shoulder yaw }
  #     - { key: RobotHardware0_tau, id: [0], label: hip yaw }

  current:
    legends:
      - { key: RobotHardware0_tau, id: [32], label: hip-innner }
      - { key: RobotHardware0_tau, id: [33], label: hip-outer  }
      - { key: RobotHardware0_tau, id: [34], label: knee }
#      - { key: RobotHardware0_tau, id: [35], label: ankle-innner }
#      - { key: RobotHardware0_tau, id: [36], label: ankle-outer  }
      - { key: RobotHardware0_tau, id: [44], label: elbow }
#      - { key: RobotHardware0_tau, id: [46], label: wrist-inner }
#      - { key: RobotHardware0_tau, id: [47], label: wrist-outer }
      - { key: RobotHardware0_tau, id: [42], label: waist right}
      - { key: RobotHardware0_tau, id: [43], label: waist left }
      - { key: RobotHardware0_tau, id: [16], label: shoulder roll/pitch}
      - { key: RobotHardware0_tau, id: [17], label: shoulder roll/pitch}
      - { key: RobotHardware0_tau, id: [18], label: shoulder yaw }
