main:
  rleg cylinder:
    legends:
      - { key: RobotHardware0_q_lin, id: [32], label: crotch-inner }
      - { key: RobotHardware0_q_lin, id: [33], label: crotch-outer }
      - { key: RobotHardware0_q_lin, id: [34], label: knee }
      - { key: RobotHardware0_q_lin, id: [35], label: ankle-inner }
      - { key: RobotHardware0_q_lin, id: [36], label: ankle-outer }
      - { key: atc_q, id: [32], label: ref crotch-inner}
      - { key: atc_q, id: [33], label: ref crotch-outer}
      - { key: atc_q, id: [34], label: ref knee }
      - { key: atc_q, id: [35], label: ref ankle-inner }
      - { key: atc_q, id: [36], label: ref ankle-outer }

  lleg cylinder:
    legends:
      - { key: RobotHardware0_q_lin, id: [32], label: crotch-inner }
      - { key: RobotHardware0_q_lin, id: [33], label: crotch-outer }
      - { key: RobotHardware0_q_lin, id: [34], label: knee }
      - { key: RobotHardware0_q_lin, id: [35], label: ankle-inner }
      - { key: RobotHardware0_q_lin, id: [36], label: ankle-outer }
      - { key: atc_q, id: [32], label: ref crotch-inner}
      - { key: atc_q, id: [33], label: ref crotch-outer}
      - { key: atc_q, id: [34], label: ref knee }
      - { key: atc_q, id: [35], label: ref ankle-inner }
      - { key: atc_q, id: [36], label: ref ankle-outer }

  rarm cylinder:
    legends:
      - { key: RobotHardware0_q_lin, id: [44], label: elbow }
      - { key: RobotHardware0_q_lin, id: [46], label: wrist-inner }
      - { key: RobotHardware0_q_lin, id: [47], label: wrist-outer }
      - { key: atc_q, id: [44], label: ref elbow }
      - { key: atc_q, id: [46], label: ref wrist-inner }
      - { key: atc_q, id: [47], label: ref wrist-outer }

  larm cylinder:
    legends:
      - { key: RobotHardware0_q_lin, id: [45], label: elbow }
      - { key: RobotHardware0_q_lin, id: [48], label: wrist-inner }
      - { key: RobotHardware0_q_lin, id: [49], label: wrist-outer }
      - { key: atc_q, id: [45], label: ref elbow }
      - { key: atc_q, id: [48], label: ref wrist-inner }
      - { key: atc_q, id: [49], label: ref wrist-outer }

  torso cylinder:
    legends:
      - { key: RobotHardware0_q_lin, id: [42], label: waist-right }
      - { key: RobotHardware0_q_lin, id: [43], label: waist-left }
      - { key: atc_q, id: [42], label: ref waist-right }
      - { key: atc_q, id: [43], label: ref waist-left }
